name: CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Docker Compose
        uses: docker/compose-action@v2
        with:
          compose-file: docker-compose.yml

      - name: Run Jest tests
        run: docker-compose run --rm app npm run test
