services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    restart: on-failure
    networks:
      - internal-network

  redis:
    image: redis:7.0-alpine
    volumes:
      - redis-config:/usr/local/etc/redis
      - redis-data:/data
    networks:
      - internal-network
    environment:
      - REDIS_PASSWORD=password
    ports:
      - 6379:6379

networks:
  internal-network:

volumes:
  redis-config:
  redis-data:
