services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - redis
    restart: on-failure
    networks:
      - internal-network

  redis:
    image: redis:7.0-alpine
    networks:
      - internal-network
    environment:
      - REDIS_PASSWORD=password
    ports:
      - 6379:6379

networks:
  internal-network:
