name: test

on:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_head }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: .ci/docker-compose.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Docker Compose
        run: docker-compose up -d

      - name: Run tests
        run: docker-compose run app npm run test
